# general settings
name: stage1
model_type: VQGANModel
num_gpu: 4
manual_seed: 42

# dataset and data loader settings
datasets:
  train:
    name: bfvr
    type: bfvr_Dataset
    dataroot_gt: [ 
                  '/data/vfhq', 
                  ]
    filename_tmpl: '{}'
    io_backend:
      type: disk

    in_size: 256
    gt_size: 256
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    use_hflip: false
    use_corrupt: false # for VQGAN

    kernel_list: ['iso'] # 'iso', 'aniso'
    kernel_prob: [1.0]
    blur_kernel_size: 11
    blur_sigma: [2, 5]
    downsample_range: [2, 4]
    noise_range: [0, 5]
    crf_range: [18, 25]
    jpeg_range: [50, 90]
    mask_range: [48, 96]
    flick_range: [0.5, 1.5]
    flick_probe: 0.3

    gaussian_en: 0
    grey_en: 0
    color_jitter_en: 0
    noise_en: 0
    ffmpeg_en: 0
    downsample_en: 0
    inpaint_en: 0
    flick_en: 0
    flick_sd_en: 0

    latent_gt_path: ~ # without pre-calculated latent code

    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 1
    dataset_enlarge_ratio: 1

    prefetch_mode: cpu
    num_prefetch_queue: 1
    
# network structures
network_g:
  type: VQAutoEncoder3D
  img_size: 256
  nf: 32
  ch_mult: [1, 2, 4, 8]
  quantizer: 'nearest'
  codebook_size: 1024

network_d:
  type: VQGANDiscriminator3D
  nc: 3
  ndf: 32

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  pretrain_network_d: ~
  strict_load_d: true
  resume_state: ~

train:
  optim_g:
    type: Adam
    lr: !!float 7e-5
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 7e-5
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [250000]
    restart_weights: [1]
    eta_min: !!float 6e-5 # no lr reduce in official vqgan code

  total_iter: 250000

  warmup_iter: -1  # no warm up
  ema_decay: 0.995 # GFPGAN: 0.5**(32 / (10 * 1000) == 0.998; Unleashing: 0.995

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  perceptual_opt:
    type: LPIPSLoss
    loss_weight: 1.0
    use_input_norm: true
    range_norm: true

  gan_opt:
    type: GANLoss
    gan_type: hinge
    loss_weight: !!float 0.5 # adaptive_weighting

  net_g_start_iter: 0
  net_d_iters: 1
  net_d_start_iter: 2001
  manual_seed: 42

# validation settings
val:
  val_freq: !!float 5e10 # no validation
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false

# logging settings
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 50000
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: gloo
  port: 29414

find_unused_parameters: true
